version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iamkroot
      - MYSQL_PASSWORD=iamkroot
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8081:80
    links:
      - db
    volumes:
      - /data/nextcloud:/var/www/html
      - /data/nextcloud-data/:/data  
    environment:
      - MYSQL_PASSWORD=iamkroot
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
