---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /data/config/radarr:/config
      - /hddmain/media/movies:/data/media/movies #optional
      - /hddmain/torrent:/data/torrent #optional
    ports:
      - 7878:7878
    restart: unless-stopped
