version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true #optional
      #optional
    volumes:
      - /data/config/jackett:/config

    ports:
      - 9117:9117
    restart: unless-stopped
